# -*- coding: utf-8 -*-

sudo: required
services:
  - docker

language: python

python:
  #- "2.7"
  - "3.5"

before_install:
  - pip --version
  - docker --version
  - docker-compose --version

install:
  - pip install -U pytest

before_script:
  # Pre-cache images to prevent timeout in service availability checks.
  - docker-compose -f tests/docker-compose.yml pull
  - docker-compose -f tests/docker-compose.yml build
  - docker-compose -f tests/docker-compose.yml up -d

script:
  #- if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then tox -e py27; fi
  #- if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then curl http://localhost; fi
  - pytest tests/
  - curl http://localhost:5000
  - curl http://127.0.0.1:5000

after_script:
  # Always leave a clean slate.
  - docker-compose -f tests/docker-compose.yml down

#after_success:
#  - coveralls

notifications:
  email:
    recipients:
      - efrain.gonzalez@gmail.com
    on_success: always # default: change
    on_failure: always # default: always







